name: Trigger E2E Workflow

on:
  push:
    branches:
      - "main"
      - "release-**"
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - '.github/workflows/e2e.yml'
  pull_request:
    branches:
      - "main"
      - "release-**"
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - '.github/workflows/e2e.yml'

jobs:
  e2e-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dump GitHub context
        run: |
          echo "event_name: ${{ github.event_name }}"
          echo "pull_request.number: ${{ github.event.pull_request.number }}"
          echo "ref_name: ${{ github.ref_name }}"

      - name: Trigger E2E Workflow for a PR
        if: github.event_name == 'pull_request'
        id: trigger-workflow-pr
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "E2E (NVIDIA Tesla T4 x1)"
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ref: 'main'
          inputs: >-
            {
              "pr_or_branch": "${{ github.event.pull_request.number }}"
            }

      - name: Trigger E2E Workflow for a branch
        if: github.event_name == 'push'
        id: trigger-workflow-branch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "E2E (NVIDIA Tesla T4 x1)"
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ref: 'main'
          inputs: >-
            {
              "pr_or_branch": "${{ github.ref_name }}"
            }`

      - name: E2E Workflow will begin shortly
        run: |
          echo "E2E Workflow for PR ${{ github.event.pull_request.number }} has been triggered."
          echo "It will show up in the status checks shortly."
